language: node_js

node_js:
  - 'stable'

sudo: required

services:
  - 'docker'

cache:
  directories:
    - 'node_modules'

before_script:
  - npm install

script:
  - npm run-script test
  - make dockerbuild
  - make dockerpush
